### PR TITLE
Added hash code for RosBag object

### PR DESCRIPTION
**Pull request by Kytzis**

### CODE REVIEW

**Comment by henrikhorluck** [comment]
Why do you need to either 1. compare ROSBag or 2. check for equality outside of their path?

**Comment by Kytzis** [comment]
> 

We thought we could try using hash codes to know what Telemetry source a datachannel came from. And thought it made sense for the hash code of RosTelemetrySource to be based on a hash of the underlying bag. When it comes to using more than path, it just seemed more right to use more of the content?

**Comment by henrikhorluck** [comment]
> We thought we could try using hash codes to know what Telemetry source a datachannel came from. And thought it made sense for the hash code of RosTelemetrySource to be based on a hash of the underlying bag. When it comes to using more than path, it just seemed more right to use more of the content?

Why do you need to override the hashcode for that? Why would you ever end up reading the same bag twice and then need to check if the bag is the same as an integrity check, which is extremely performance heavy due to the way you have to read the entire bag (potentially multiple gigabytes) — which anyway does not actually guarantee it is equal since it 1. does not look at messages, and 2. you only compare the topic name — not the MD5 sum of the topic so they might have different underlying types. (Also nothing but the path-comparison is converted in the test, also now the HashCode is only defined/changes after you call `Read` which is weird behavior)

> And thought it made sense for the hash code of RosTelemetrySource to be based on a hash of the underlying bag.

Then why not implement it on `RosTelemetrySource` if that is what you want?

Anyway: I suggest using just a URI as the source-specifier: https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-6.0
E.g. `ros://path/to/file.bag` or `uavcan://IP?` and implement useful extension methods instead

**Comment by Kytzis** [comment]
We can try to implement it using URI yes, we just didnt know what was a smart solution

**Pull request closed without merging**
